### ISSUE TITLE
add channel logging 

### ISSUE THREAD

**Issue by jbasalone** [lukazbaum/discordjs-command-handler#8]
## Feature Description
Ability to set preference in each command file on a channel to log command usage and an embed template 

## Problem and Motivation
I have to add a line to each command if I want it logged to a discord channel that the command was ran. I attached a sample. 
<img width="457" alt="Screenshot 2024-07-23 at 10 52 29 AM" src="https://github.com/user-attachments/assets/f7aa175b-a5b6-438f-9965-b139758459ac">

## Additional Context
Add any other context or screenshots about the feature request here. If this feature is inspired by something else, please provide references.

**Comment by lukazbaum** [comment]
Do you mean a channel Id argument that will send an embed to the specified channel as a notification when the command is executed?

**Comment by jbasalone** [comment]
yes yes

**Comment by lukazbaum** [comment]
(still working on the new version but it will take a while.)

**Comment by jbasalone** [comment]
the other thing I was thinking would be cool is to have a master config list for commands and allowed servers/channels etc. 

Like a YAML file or something.  Would maybe have to implement some way of tracking the command with an id or something.

Guild -
|_command-id 
|__channelwhitelist:

**Comment by lukazbaum** [comment]
Like this?:
```yaml
guilds:
  - guild_id: 123456789012345678
    commands:
      - command_name: "ban" # Maybe id instead of name
        channel_whitelist:
          - 987654321098765432
          - 876543210987654321
      - command_name: "kick"
        channel_whitelist:
          - 123456789098765432
```
